#################################
#        DATABASE SERVICE
#################################
apiVersion: v1
kind: Service
metadata:
  # this is the name we used in our Connection String
  name: db
  labels:
    app: realebot
    tier: database
spec:
  type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: realebot
    tier: database

#################################
#        PERSISTENT VOLUME
#################################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 30Gi

#################################
#        DATABASE WORKLOAD
#################################
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: realebot
    tier: database
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: realebot
        tier: database
    spec:
      containers:
        - image: postgres:11.4-alpine
          name: postgresql
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: fullstack
            - name: POSTGRES_PASSWORD
              value: admin
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: postgres-data
